# Generated by Django 5.2.3 on 2025-08-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_billing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='name',
        ),
        migrations.AddField(
            model_name='billing',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
